
#Warped Book Configuration
[warpedbook]

	[warpedbook.warpedbook]
		#Durability cost mode, NOCOST = 0, STANDARD = 1, NOREPAIR = 2
		#NOCOST : Book will no longer take damage from teleporting.
		#STANDARD : Books take damage on use & can be fed to repair damage.
		#NOREPAIR : Book will be destroyed like any other damagable item, mending still works.
		#Range: 0 ~ 2
		usage_mode = 1
		#Durability cost for book when teleporting
		#Range: 1 ~ 100
		usage_cost = 5
		#Durability repaired when book is fed
		#Range: 1 ~ 100
		feed_value = 25
		#Cooldown between teleportions (similar to an enderpearl)
		#Range: > 0
		teleport_cooldown = 300
		#Cooldown multiplier applied by the Energetic enchant
		#Range: 0.0 ~ 1.0
		energetic_percent = 0.5

