
#Server configuration settings
[server]
	#The number of hours the player will be offline before deactivating (default 2 days)
	#Range: 1 ~ 8760
	hoursBeforeDeactivation = 48
	#Width/length of chunks to be loaded, it is recommend this is an odd number (max 25)
	#Range: 1 ~ 25
	chunkLoaderWidth = 3
	#Disables Chunk loading, use if there is a crash happening in a chunk loaded area
	emergencymode = false

